### ISSUE TITLE
404 on status update

### ISSUE THREAD

**Issue by crsantos** [mattgemmell/MGTwitterEngine#107]
Has anyone notice any change on the last hours? Maybe an API update of twitter.

I'm receiving ALWAYS 404 on any status update on
- (void)requestFailed:(NSString *)connectionIdentifier withError:(NSError *)error

**Comment by keab42** [comment]
Twitter turned off the API Endpoints at twitter.com

There is a quick fix:

You need to find the Line:

#define TWITTER_DOMAIN

And update it to "api.twitter.com/1" 

Unfortunately that will only work until the beginning of 2013 when Twitter turns off the v1.0 api in favour of 1.1

Unfortunately in my experiments today updating to "api.twitter.com/1.1" (The URL for the 1.1 API) doesn't work with my own implementation as apparently the oAuth requirements are different.

I'd be interested to know if anybody has a more complete solution that will work with 1.1

**Comment by crsantos** [comment]
Forgot to check the endpoints, thanks :)
Although, I have to re-think my support for Twitter sharing on iOS < 5 devices :/

**Comment by pandyakushagra** [comment]
Twitter version 1.1  support only json because with new version of twitter API it only support JSON Format see here : https://dev.twitter.com/docs/api/1.1/overview#JSON_support_only

so in "MGTWITTERENGINE" to work with this need set YAJL to 1 and then need to import YAJL library in it.
Then it will work for 1.1.

**Comment by bayfatih2000** [comment]
I don't understand :((
How can I work with V1.1?
